openapi: 3.0.0
info:
  title: RS Urip Sumoharjo API
  contact: {}
  version: "1.0"
servers:
  - url: https://rs-urip-sumoharjo-api.herokuapp.com/api/v1
    variables: {}
paths:
  /admin/login:
    post:
      tags:
        - Administration
      summary: Login Admin
      description: Login for Hospital Administrator
      operationId: LoginAdmin
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginAdminRequest"
            example:
              email: samuel@yahoo.com
              password: secret
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /admin/register:
    post:
      tags:
        - Administration
      summary: Register Admin
      description: Registration for Administrator
      operationId: RegisterAdmin
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterAdminRequest"
            example:
              name: Samual Jackson
              email: samuel@yahoo.com
              password: secret
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /doctors/{id}:
    get:
      tags:
        - Doctor
      summary: Get Doctor by ID
      description: Get doctor by ID
      operationId: GetDoctorbyID
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          style: simple
          schema:
            type: string
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /doctors/admin/{id}:
    delete:
      tags:
        - Doctor
      summary: Delete doctor
      description: Delete doctor by Id. Administrator only
      operationId: Deletedoctor
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          style: simple
          schema:
            type: string
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    patch:
      tags:
        - Doctor
      summary: Update Doctor
      description: Update Doctor schedule. Administrator only
      operationId: UpdateDoctor
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          style: simple
          schema:
            type: string
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateDoctorRequest"
            example:
              waktu: sore
              poli: Kulit Kelamin
              hari: Senin, Rabu dan Jum'at
              jam: Pkl 16.00 s/d 18.00 WIB
              gender: false
              on_call: false
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /doctors/admin:
    post:
      tags:
        - Doctor
      summary: Add Doctor
      description: Add new doctor. Administrator only.
      operationId: AddDoctor
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddDoctorRequest"
            example:
              nama: dr.Samuel Jackson
              waktu: pagi
              poli: Umum
              hari: Minggu ke-2 dan ke-4
              jam: Pkl 09.00 s/d 10.00 WIB
              gender: 1
              on_call: 1
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /doctors:
    get:
      tags:
        - Doctor
      summary: Search Doctor
      description: Search doctor using 'nama' keyword or 'poli'  or get all doctors
      operationId: SearchDoctor
      parameters:
        - in: query
          name: nama
          schema:
            type: string
          description: Mencari dokter berdasarkan nama
        - in: query
          name: poli
          schema:
            type: string
          description: Mencari dokter berdasarkan poli yang dituju
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /jobs/{id}:
    get:
      tags:
        - Job
      summary: Get Single Job
      description: Showing single job by id
      operationId: GetSingleJob
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          style: simple
          schema:
            type: string
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /jobs/admin:
    post:
      tags:
        - Job
      summary: Add Job
      description: Add new job. Administrator only
      operationId: AddJob
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddJobRequest"
            example:
              title: Perawat gigi
              pengalaman: 1
              kualifikasi:
                - Wanita
                - Pernah bekerja di klinik gigi sebagai perawat gigi
                - Minimal lulusan smk/sma
                - Untuk melakukan asistensi dokter gigi
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /jobs/admin/{id}:
    patch:
      tags:
        - Job
      summary: Update Job
      description: Update Job data. Administrator only
      operationId: UpdateJob
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          style: simple
          schema:
            type: string
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateJobRequest"
            example:
              title: Perawat gigi
              pengalaman: 2
              kualifikasi:
                - Pria
                - Pernah bekerja di klinik gigi sebagai perawat gigi
                - Minimal lulusan smk/sma
                - Untuk melakukan asistensi dokter gigi
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    delete:
      tags:
        - Job
      summary: Delete Job
      description: Delete Job. Administrator only
      operationId: DeleteJob
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          style: simple
          schema:
            type: string
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /jobs:
    get:
      tags:
        - Job
      summary: Get All Jobs
      description: Get all Job vacancies available
      operationId: GetAllJobs
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /patient/login:
    post:
      tags:
        - Patient
      summary: Login Patient
      description: Patient Login
      operationId: LoginPatient
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginPatientRequest"
            example:
              email: samuel@gmail.com
              password: secret
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /patient/register:
    post:
      tags:
        - Patient
      summary: Register Patient
      description: Patient Registration
      operationId: RegisterPatient
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterPatientRequest"
            example:
              name: Samuel Jackson
              email: samuel@gmail.com
              password: secret
              gender: 0
              age: 42
              address: Jl. Way Sekampung no 6
              phone: 2342332
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /patientdata/{id}:
    delete:
      tags:
        - Patient
      summary: Delete Patient Data
      description: Delete Patient, require patient login
      operationId: DeletePatientData
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          style: simple
          schema:
            type: string
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    patch:
      tags:
        - Patient
      summary: Update Patient Data
      description: Update current address or phone, require patient login
      operationId: UpdatePatientData
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          style: simple
          schema:
            type: string
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePatientDataRequest"
            example:
              address: Jl. Way Sekampung 95
              phone: 345829
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    get:
      tags:
        - Patient
      summary: Get Patient Data
      description: Get single patient Data, require patient login
      operationId: GetPatientData
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          style: simple
          schema:
            type: string
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /facilities:
    get:
      tags:
        - Facility
      summary: Search Facility
      description: Search facility by title or get all facilities
      operationId: SearchFacility
      parameters:
        - in: query
          name: title
          schema:
            type: string
          description: Mencari Fasilitas berdasarkan nama
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
    post:
      tags:
        - Facility
      summary: Create new Facility
      description: Create new facility. Administrator only.
      operationId: CreatenewFacility
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
                - title
                - info
                - category
                - img
              type: object
              properties:
                title:
                  type: string
                  example: Unit Gawat Darurat
                info:
                  type: string
                  example: Menyediakan penanganan awal bagi pasien yang menderita sakit dan cedera
                category:
                  type: string
                  example: poliklinik
                img:
                  type: string
        required: false
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /facilities/{id}:
    get:
      tags:
        - Facility
      summary: Get single Facility
      description: Get single facility
      operationId: GetsingleFacility
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          style: simple
          schema:
            type: string
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
    delete:
      tags:
        - Facility
      summary: Delete Facility
      description: Delete a facility by id. Administrator only.
      operationId: DeleteFacility
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          style: simple
          schema:
            type: string
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    patch:
      tags:
        - Facility
      summary: Update Facility
      description: Update a facility. Administrator only.
      operationId: UpdateFacility
      parameters:
        - name: id
          in: path
          description: ""
          required: true
          style: simple
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
                - title
                - category
                - info
                - img
              type: object
              properties:
                title:
                  type: string
                  example: I will survive again
                category:
                  type: string
                  example: rawat-jalan
                info:
                  type: string
                  example: Melihat gelombang gelombang frekuensi yang disebut ultrasound dari bilik-bilik jantung.
                img:
                  type: string
        required: false
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
components:
  schemas:
    LoginAdminRequest:
      title: LoginAdminRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: riza@yahoo.com
        password: passwordadmin
    RegisterAdminRequest:
      title: RegisterAdminRequest
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: Riza Hariati
        email: riza@yahoo.com
        password: passwordadmin
    AddDoctorRequest:
      title: AddDoctorRequest
      required:
        - nama
        - waktu
        - poli
        - hari
        - jam
        - gender
        - on_call
      type: object
      properties:
        nama:
          type: string
        waktu:
          type: string
        poli:
          type: string
        hari:
          type: string
        jam:
          type: string
        gender:
          type: integer
          format: int32
        on_call:
          type: integer
          format: int32
      example:
        nama: dr.Riza Simanjuntak
        waktu: pagi
        poli: Umum
        hari: Minggu ke-2 dan ke-4
        jam: Pkl 09.00 s/d 10.00 WIB
        gender: 1
        on_call: 1
    UpdateDoctorRequest:
      title: UpdateDoctorRequest
      required:
        - waktu
        - poli
        - hari
        - jam
        - gender
        - on_call
      type: object
      properties:
        waktu:
          type: string
        poli:
          type: string
        hari:
          type: string
        jam:
          type: string
        gender:
          type: boolean
        on_call:
          type: boolean
      example:
        waktu: sore
        poli: Kulit Kelamin
        hari: Senin, Rabu dan Jum'at
        jam: Pkl 16.00 s/d 18.00 WIB
        gender: false
        on_call: false
    AddJobRequest:
      title: AddJobRequest
      required:
        - title
        - pengalaman
        - kualifikasi
      type: object
      properties:
        title:
          type: string
        pengalaman:
          type: integer
          format: int32
        kualifikasi:
          type: array
          items:
            type: string
          description: ""
      example:
        title: Perawat gigi
        pengalaman: 1
        kualifikasi:
          - Wanita
          - Pernah bekerja di klinik gigi sebagai perawat gigi
          - Minimal lulusan smk/sma
          - Untuk melakukan asistensi dokter gigi
    UpdateJobRequest:
      title: UpdateJobRequest
      required:
        - title
        - pengalaman
        - kualifikasi
      type: object
      properties:
        title:
          type: string
        pengalaman:
          type: integer
          format: int32
        kualifikasi:
          type: array
          items:
            type: string
          description: ""
      example:
        title: Perawat gigi
        pengalaman: 2
        kualifikasi:
          - Pria
          - Pernah bekerja di klinik gigi sebagai perawat gigi
          - Minimal lulusan smk/sma
          - Untuk melakukan asistensi dokter gigi
    LoginPatientRequest:
      title: LoginPatientRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: riza@gmail.com
        password: password
    RegisterPatientRequest:
      title: RegisterPatientRequest
      required:
        - name
        - email
        - password
        - gender
        - age
        - address
        - phone
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        gender:
          type: integer
          format: int32
        age:
          type: integer
          format: int32
        address:
          type: string
        phone:
          type: integer
          format: int32
      example:
        name: Riza Simanjuntak
        email: riza@yahoo.com
        password: password
        gender: 0
        age: 42
        address: Jl. Way Sekampung no 6
        phone: 2342332
    UpdatePatientDataRequest:
      title: UpdatePatientDataRequest
      required:
        - password
        - address
      type: object
      properties:
        password:
          type: string
        address:
          type: string
      example:
        password: password
        address: Jl. Way Sekampung 95
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Misc
    description: ""
  - name: Administration
    description: ""
  - name: Doctor
    description: ""
  - name: Job
    description: ""
  - name: Patient
    description: ""
  - name: Facility
    description: ""
